# Generated by Django 3.2 on 2024-02-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240216_1515'),
        ('users', '0002_auto_20240216_2039'),
    ]

    operations = [
    ]
