# Generated by Django 4.2.10 on 2024-02-18 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_merge_0002_auto_20240216_1515_0002_auto_20240216_2039"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="myuser",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("admin", "Администратор"),
                    ("moderator", "Модератор"),
                ],
                default="user",
                max_length=150,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Имя пользователя содержит недопустимый символ",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
